channels:
  - conda-forge
dependencies:
  - rasterio=1.3.4
  - gdal=3.6.2
  - libgdal=3.6.2
  - netcdf4
  - python
  - pip
  - pip:
      - pystac
      - pystac-client
      - requests
      - jupyterlab
      - shapely
      - odc-stac
      - geopandas
      - Fiona 
      - pyproj
      - Rtree
      - matplotlib
