name: eo-mqs
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - rasterio=1.3.4
  - gdal=3.6.2
  - libgdal=3.6.2
  - netcdf4
  - python
  - pystac
  - pystac-client
  - requests
  - shapely
  - odc-stac
  - geopandas
  - fiona 
  - pyproj
  - rtree
  - jupyterlab
   # for binder
  - jupyterhub-singleuser
  - jupyter_client
  - jupyter_server
  - matplotlib-base
